#!/usr/bin/env python
import slimmer
import sys, os

if len(sys.argv) == 3:
   if os.path.isfile(sys.argv[1]) and not os.path.isfile(sys.argv[2]):
      print 'Compressing file', sys.argv[1]
      f=open(sys.argv[1], 'r')
      content=f.read()
      f.close()
      compressed=slimmer.slimmer(content)
      f=open(sys.argv[2], 'w')
      f.write(compressed)
      f.close()
      print 'done.'
